# .github/workflows/schedule_fetch.yml

name: Scheduled Fetch Commits

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./   # корень репозитория

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_commits (writes leaderboard.json & commit_cache.json)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_commits.py

      - name: Show diff for debug
        run: git status && git diff

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # добавляем только файлы, которые точно должны измениться
          git add leaderboard.json commit_cache.json

          # если есть staged изменения — пушим
          if git diff --cached --quiet; then
            echo "✔ No changes detected."
          else
            git commit -m "Update leaderboard.json and commit_cache.json"
            git push
          fi
