# .github/workflows/schedule_fetch.yml

name: Scheduled Fetch Commits

# Только один активный запуск в группе “scheduled-fetch-commits”
concurrency:
  group: scheduled-fetch-commits
  cancel-in-progress: false

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch_commits (writes leaderboard.json & cache.json)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_commits.py

      - name: Show diff for debug
        run: |
          git status
          git diff

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # добавляем leaderboard.json и cache.json
          git add leaderboard.json cache.json

          if git diff --cached --quiet; then
            echo "✔ No changes to commit"
          else
            git commit -m "Update leaderboard.json and cache.json"
            git push
          fi
